FROM node:20.12-bullseye-slim

ARG DB_HOST=$DB_HOST
ENV DB_HOST=$DB_HOST
ARG DB_PORT=$DB_PORT
ENV DB_PORT=$DB_PORT
ARG DB_DATABASE=$DB_DATABASE
ENV DB_DATABASE=$DB_DATABASE
ARG DB_USERNAME=$DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME
ARG DB_PASSWORD=$DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
ARG AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
ENV AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
ARG AZURE_STORAGE_CONTAINER_NAME=$AZURE_STORAGE_CONTAINER_NAME
ENV AZURE_STORAGE_CONTAINER_NAME=$AZURE_STORAGE_CONTAINER_NAME

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main"]
